version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  build:
    commands:
      # 1. 백엔드 빌드
      - echo "Backend Build Started..."
      - cd backend/demo
      - chmod +x gradlew
      - ./gradlew build
      - cd ../..

      # 2. 프론트엔드 빌드
      - echo "Frontend Build Started..."
      - cd frontend
      # - npm install (이미 package.json을 올리셨다면 주석 해제하거나 그대로 두세요)
      - npm install
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Moving Backend Artifact to Frontend Dist folder..."
      
      # [추가] 불필요한 'plain' jar 파일 삭제 (이게 방해꾼입니다!)
      - rm -f backend/demo/build/libs/*-plain.jar
      
      # 이제 파일이 하나만 남았으므로 안전하게 복사됩니다.
      - cp backend/demo/build/libs/*.jar frontend/dist/application.jar

artifacts:
  files:
    # 이제 frontend/dist 안에 모든 게(html, js, jar) 다 들어있습니다.
    - '**/*'
  base-directory: frontend/dist
  discard-paths: no